version: "3.7"
services:
  gateway:
    image: ${REGISTRY}/broker-gateway:${IMAGE_TAG}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api

  frontend:
    image: ${REGISTRY}/broker-frontend:${IMAGE_TAG}
    restart: always
    depends_on:
      - api-php-fpm

  api:
    image: ${REGISTRY}/broker-api:${IMAGE_TAG}
    restart: always
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/broker-api-php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_DEBUG: 0

  api-php-cli:
    image: ${REGISTRY}/broker-api-php-cli:${IMAGE_TAG}
